export type StateCenter = {
  name: string;
  longitude: number;
  latitude: number;
};

export const US_STATE_CENTERS: Record<string, StateCenter> = {
  AL: { name: 'Alabama', longitude: -86.8, latitude: 32.8 },
  AK: { name: 'Alaska', longitude: -152.4, latitude: 64.2 },
  AZ: { name: 'Arizona', longitude: -111.9, latitude: 34.3 },
  AR: { name: 'Arkansas', longitude: -92.4, latitude: 34.9 },
  CA: { name: 'California', longitude: -119.7, latitude: 36.8 },
  CO: { name: 'Colorado', longitude: -105.5, latitude: 39.0 },
  CT: { name: 'Connecticut', longitude: -72.7, latitude: 41.6 },
  DE: { name: 'Delaware', longitude: -75.5, latitude: 39.0 },
  DC: { name: 'District of Columbia', longitude: -77.0, latitude: 38.9 },
  FL: { name: 'Florida', longitude: -81.7, latitude: 27.8 },
  GA: { name: 'Georgia', longitude: -83.4, latitude: 32.7 },
  HI: { name: 'Hawaii', longitude: -157.5, latitude: 20.9 },
  ID: { name: 'Idaho', longitude: -114.6, latitude: 44.1 },
  IL: { name: 'Illinois', longitude: -89.4, latitude: 40.0 },
  IN: { name: 'Indiana', longitude: -86.1, latitude: 40.0 },
  IA: { name: 'Iowa', longitude: -93.5, latitude: 42.0 },
  KS: { name: 'Kansas', longitude: -98.4, latitude: 38.5 },
  KY: { name: 'Kentucky', longitude: -84.3, latitude: 37.5 },
  LA: { name: 'Louisiana', longitude: -91.9, latitude: 31.0 },
  ME: { name: 'Maine', longitude: -69.4, latitude: 45.3 },
  MD: { name: 'Maryland', longitude: -76.6, latitude: 39.0 },
  MA: { name: 'Massachusetts', longitude: -71.8, latitude: 42.3 },
  MI: { name: 'Michigan', longitude: -84.6, latitude: 44.3 },
  MN: { name: 'Minnesota', longitude: -94.7, latitude: 46.3 },
  MS: { name: 'Mississippi', longitude: -89.7, latitude: 32.7 },
  MO: { name: 'Missouri', longitude: -92.5, latitude: 38.5 },
  MT: { name: 'Montana', longitude: -110.5, latitude: 46.9 },
  NE: { name: 'Nebraska', longitude: -99.8, latitude: 41.5 },
  NV: { name: 'Nevada', longitude: -116.6, latitude: 39.3 },
  NH: { name: 'New Hampshire', longitude: -71.6, latitude: 43.7 },
  NJ: { name: 'New Jersey', longitude: -74.5, latitude: 40.1 },
  NM: { name: 'New Mexico', longitude: -106.0, latitude: 34.5 },
  NY: { name: 'New York', longitude: -75.5, latitude: 43.0 },
  NC: { name: 'North Carolina', longitude: -79.0, latitude: 35.5 },
  ND: { name: 'North Dakota', longitude: -100.5, latitude: 47.5 },
  OH: { name: 'Ohio', longitude: -82.8, latitude: 40.3 },
  OK: { name: 'Oklahoma', longitude: -97.5, latitude: 35.5 },
  OR: { name: 'Oregon', longitude: -120.6, latitude: 44.0 },
  PA: { name: 'Pennsylvania', longitude: -77.8, latitude: 40.9 },
  PR: { name: 'Puerto Rico', longitude: -66.5, latitude: 18.2 },
  RI: { name: 'Rhode Island', longitude: -71.5, latitude: 41.7 },
  SC: { name: 'South Carolina', longitude: -80.9, latitude: 33.8 },
  SD: { name: 'South Dakota', longitude: -100.2, latitude: 44.4 },
  TN: { name: 'Tennessee', longitude: -86.4, latitude: 35.8 },
  TX: { name: 'Texas', longitude: -99.9, latitude: 31.0 },
  UT: { name: 'Utah', longitude: -111.7, latitude: 39.3 },
  VT: { name: 'Vermont', longitude: -72.6, latitude: 44.0 },
  VA: { name: 'Virginia', longitude: -78.7, latitude: 37.5 },
  VI: { name: 'Virgin Islands', longitude: -64.8, latitude: 18.3 },
  WA: { name: 'Washington', longitude: -120.5, latitude: 47.4 },
  WV: { name: 'West Virginia', longitude: -80.6, latitude: 38.6 },
  WI: { name: 'Wisconsin', longitude: -89.6, latitude: 44.6 },
  WY: { name: 'Wyoming', longitude: -107.6, latitude: 43.0 },
};
